=== lequockhanh19521680/KhangSave/innova 2015/rm21q3ev/ewd/dtd/codelist.dtd
<!--
	EWD Item List DTD
	
	Copyright (c) 2000-2004 SHINTEC HOZUMI Co.,LTD.
	All Rights Reserved. 
	
	for (Parts) Code List in figure
-->



<!ENTITY % Number	"CDATA">
<!ENTITY % code		"CDATA">
	<!-- one or more digits -->
<!ENTITY % InfoType	"(system | routing | relay)">
<!ENTITY % PartsType	"(conn | w2w | jb | jbc | rb | jc | gp | sp | fl | relay | name)">
	<!-- 
		conn: connector
		w2w: Wire and Wire
		jb: Junction Block
		jbc: Junction Block Connector
		rb: Relay Block
		jc: Junction Connector
		gp: Ground Point
		sp: Splice Point
		fl: Fusible Link
		relay: Relay
		name: Named Item
	-->



<!ELEMENT	CodeList	(Code*)>
<!ELEMENT	Code		(refs*)>
<!ELEMENT	refs		EMPTY>



<!ATTLIST CodeList
	ver		CDATA		"1.0"
	type		%InfoType;	#REQUIRED
	pubno		CDATA		#REQUIRED
>

<!ATTLIST Code
	id		CDATA		#REQUIRED
	subcode		CDATA		#IMPLIED
	type		%PartsType;	#REQUIRED
 	pinNo		%Number;	#IMPLIED
>

<!ATTLIST refs
	type		%InfoType;	#REQUIRED
	code		%code;		#REQUIRED
>

=== lequockhanh19521680/KhangSave/innova 2015/rm21q3ev/ewd/contents/routing/codes/1TRFEL-P2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE CodeList SYSTEM "../../../dtd/codelist.dtd">
<CodeList pubno="EM21Q2EV" type="routing">
	<Code id="S1" type="conn" subcode="">
		<refs type="system" code="SYS025"/>
		<refs type="system" code="SYS037"/></Code>
	<Code id="I2" type="conn" subcode="">
		<refs type="system" code="SYS031"/>
		<refs type="system" code="SYS032"/></Code>
	<Code id="I1" type="conn" subcode="">
		<refs type="system" code="SYS031"/>
		<refs type="system" code="SYS032"/></Code>
	<Code id="T21" type="conn" subcode="B">
		<refs type="system" code="SYS024"/></Code>
	<Code id="I3" type="conn" subcode="">
		<refs type="system" code="SYS031"/>
		<refs type="system" code="SYS032"/></Code>
	<Code id="T17" type="conn" subcode="A">
		<refs type="system" code="SYS024"/></Code>
	<Code id="T8" type="conn" subcode="A">
		<refs type="system" code="SYS024"/></Code>
	<Code id="T18" type="conn" subcode="B">
		<refs type="system" code="SYS024"/></Code>
	<Code id="S2" type="conn" subcode="">
		<refs type="system" code="SYS029"/></Code>
	<Code id="J1" type="conn" subcode="">
		<refs type="system" code="SYS009"/>
		<refs type="system" code="SYS013"/>
		<refs type="system" code="SYS023"/>
		<refs type="system" code="SYS024"/>
		<refs type="system" code="SYS031"/>
		<refs type="system" code="SYS037"/>
		<refs type="system" code="SYS040"/>
		<refs type="system" code="GP"/></Code>
	<Code id="T7" type="conn" subcode="A">
		<refs type="system" code="SYS024"/></Code>
	<Code id="T19" type="conn" subcode="B">
		<refs type="system" code="SYS024"/></Code>
	<Code id="J37" type="conn" subcode="">
		<refs type="system" code="SYS031"/>
		<refs type="system" code="SYS040"/></Code>
	<Code id="N1" type="conn" subcode="">
		<refs type="system" code="SYS003"/>
		<refs type="system" code="SYS018"/>
		<refs type="system" code="SYS031"/>
		<refs type="system" code="SYS033"/>
		<refs type="system" code="SYS040"/></Code>
	<Code id="I4" type="conn" subcode="">
		<refs type="system" code="SYS031"/>
		<refs type="system" code="SYS032"/></Code>
	<Code id="S3" type="conn" subcode="">
		<refs type="system" code="SYS001"/>
		<refs type="system" code="SYS005"/>
		<refs type="system" code="SYS002"/>
		<refs type="system" code="SYS007"/>
		<refs type="system" code="SYS008"/>
		<refs type="system" code="SYS018"/>
		<refs type="system" code="SYS031"/>
		<refs type="system" code="SYS035"/>
		<refs type="system" code="SYS040"/></Code>
	<Code id="W1" type="conn" subcode="">
		<refs type="system" code="SYS031"/>
		<refs type="system" code="SYS040"/></Code>
	<Code id="T1" type="conn" subcode="">
		<refs type="system" code="SYS031"/>
		<refs type="system" code="SYS040"/></Code>
	<Code id="W3" type="conn" subcode="">
		<refs type="system" code="SYS010"/></Code>
	<Code id="S7" type="conn" subcode="B">
		<refs type="system" code="SYS033"/></Code>
	<Code id="T16" type="conn" subcode="A">
		<refs type="system" code="SYS024"/></Code>
	<Code id="T22" type="conn" subcode="B">
		<refs type="system" code="SYS024"/></Code>
	<Code id="S6" type="conn" subcode="A">
		<refs type="system" code="SYS033"/></Code>
	<Code id="P1" type="conn" subcode="">
		<refs type="system" code="SYS031"/></Code>
	<Code id="V3" type="conn" subcode="">
		<refs type="system" code="SYS031"/></Code>
	<Code id="K1" type="conn" subcode="">
		<refs type="system" code="SYS031"/></Code>
	<Code id="N2" type="conn" subcode="A">
		<refs type="system" code="SYS032"/></Code>
	<Code id="N2" type="conn" subcode="B">
		<refs type="system" code="SYS032"/></Code>
	<Code id="S5" type="conn" subcode="">
		<refs type="system" code="SYS029"/></Code>
	<Code id="P2" type="conn" subcode="">
		<refs type="system" code="SYS034"/>
		<refs type="system" code="SYS035"/></Code>
	<Code id="R1" type="conn" subcode="">
		<refs type="system" code="SYS021"/></Code>
	<Code id="S4" type="conn" subcode="">
		<refs type="system" code="SYS029"/></Code>
	<Code id="W2" type="conn" subcode="">
		<refs type="system" code="SYS010"/></Code>
	<Code id="T5" type="conn" subcode="">
		<refs type="system" code="SYS040"/></Code>
	<Code id="T4" type="conn" subcode="">
		<refs type="system" code="SYS040"/></Code>
</CodeList>
