=== lequockhanh19521680/KhangSave/innova 2015/rm21q3ev/ewd/dtd/connect.dtd
<!--
	Connection List DTD

	Copyright (c) 2000-2005 SHINTEC HOZUMI Co.,LTD.
	All Rights Reserved. 


	use for parts link info
	oversea's EWD

	ver 1.10	2004/02/19
	ver 1.20	2004/10/08
		add attribute subcode

	ver 1.21	2005/04/13
		add a attribute of pubno to root element
-->

<!-- <?xml version="1.0" encoding="UTF-8"?> -->
<!-- XML DTD for TOYOTA EWD connector -->



<!ENTITY % Number	"CDATA">
<!ENTITY % PinCode	"CDATA">
<!ENTITY % WireColor	"CDATA">
<!ENTITY % Spec		"CDATA">
<!ENTITY % Sex		"(male | female)">
<!ENTITY % PartsType	"(conn | w2w | jb | jbc | rb  | relay | jc | gp | sp | fl | NON)">
	<!--
		conn: connector
		w2w: Wire and Wire
		jb: Junction Block
		jbc: Junction Block Connector
		rb:	Relay Block
		relay: Relay
		jc: Junction Connector
		gp: Ground Point
		sp: Splice Point
		fl: Fusible Link
	-->



<!ELEMENT	connectionList	(connector)+>
<!ELEMENT	connector	(pin)+>
<!ELEMENT	pin		(junction?, (line?|EMPTY))>
<!ELEMENT	line		(connector)>
<!ELEMENT	junction	(point)+>
<!ELEMENT	point		(pin)+>



<!ATTLIST connectionList
	ver		CDATA	"1.0"
	pubno	CDATA	#REQUIRED
>

<!ATTLIST connector
	type		%PartsType;	#REQUIRED
	code		%PinCode;	#IMPLIED
	subcode		%PinCode;	#IMPLIED
	sex		%Sex;		#IMPLIED
	spec		%Spec;		#IMPLIED
>

<!ATTLIST pin
	no		%Number;	#IMPLIED
	spec		%Spec;		#IMPLIED
>

<!ATTLIST line
	id		%Number;	#REQUIRED
	color		%WireColor;	#REQUIRED
	groupID		%Number;	#IMPLIED
	spec		%Spec;		#IMPLIED
>

<!ATTLIST point
	 code		%PinCode;	#IMPLIED
>

=== lequockhanh19521680/KhangSave/innova 2015/rm21q3ev/ewd/contents/system/connect/SRS.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE connectionList SYSTEM "../../../dtd/connect.dtd">
<connectionList pubno="EM21Q2EV">
	<connector type="conn" code="J28" subcode="B">
		<pin no="12">
			<line id="1" color="W-B">
				<connector type="gp" code="IG">
					<pin/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="J27" subcode="A">
		<pin no="10">
			<line id="2" color="Y">
				<connector type="conn" code="C10" subcode="A">
					<pin no="22" spec="Before Feb. 2012 Production"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="J27" subcode="A">
		<pin no="10">
			<line id="2" color="Y">
				<connector type="conn" code="C20" subcode="C">
					<pin no="22" spec="From Feb. 2012 Production"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="C10" subcode="A">
		<pin no="21" spec="Before Feb. 2012 Production">
			<line id="3" color="B-O">
				<connector type="jbc" code="2D">
					<pin no="1"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="C20" subcode="C">
		<pin no="21" spec="From Feb. 2012 Production">
			<line id="3" color="B-O">
				<connector type="jbc" code="2D">
					<pin no="1"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="jbc" code="2O">
		<pin no="21">
			<line id="4" color="B-Y">
				<connector type="conn" code="C10" subcode="A">
					<pin no="20" spec="Before Feb. 2012 Production"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="jbc" code="2O">
		<pin no="21">
			<line id="4" color="B-Y">
				<connector type="conn" code="C20" subcode="C">
					<pin no="20" spec="From Feb. 2012 Production"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="jbc" code="2O">
		<pin no="5">
			<line id="5" color="B-Y">
				<connector type="conn" code="D3">
					<pin no="11"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="jbc" code="2B">
		<pin no="3">
			<line id="6" color="B-Y">
				<connector type="conn" code="A19">
					<pin no="14"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="A19">
		<pin no="16">
			<line id="7" color="W">
				<connector type="jbc" code="2B">
					<pin no="7"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="jbc" code="2Q">
		<pin no="22">
			<line id="8" color="R-Y">
				<connector type="conn" code="D3">
					<pin no="7"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="A19">
		<pin no="15">
			<line id="9" color="P-B">
				<connector type="jbc" code="2B">
					<pin no="4"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="jbc" code="2Q">
		<pin no="21">
			<line id="10" color="P-B">
				<connector type="conn" code="D3">
					<pin no="13"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="A21">
		<pin no="1">
			<line id="11" color="Y-B">
				<connector type="conn" code="A19">
					<pin no="5"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="A19">
		<pin no="21">
			<line id="12" color="B-O">
				<connector type="jbc" code="2B">
					<pin no="8"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="A21">
		<pin no="2">
			<line id="13" color="Y">
				<connector type="conn" code="A19">
					<pin no="6"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="A19">
		<pin no="28">
			<line id="14" color="BR">
				<connector type="w2w" code="II1" sex="male">
					<pin no="4"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="w2w" code="II1" sex="female">
		<pin no="4">
			<line id="15" color="BR">
				<connector type="conn" code="A5" subcode="A">
					<pin no="1" spec="Before Feb. 2012 Production"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="w2w" code="II1" sex="female">
		<pin no="4">
			<line id="15" color="BR">
				<connector type="conn" code="A34" subcode="B">
					<pin no="1" spec="From Feb. 2012 Production"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="A19">
		<pin no="30">
			<line id="16" color="W-R">
				<connector type="w2w" code="II1" sex="male">
					<pin no="3"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="w2w" code="II1" sex="female">
		<pin no="3">
			<line id="17" color="W-R">
				<connector type="conn" code="A5" subcode="A">
					<pin no="2" spec="Before Feb. 2012 Production"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="w2w" code="II1" sex="female">
		<pin no="3">
			<line id="17" color="W-R">
				<connector type="conn" code="A34" subcode="B">
					<pin no="2" spec="From Feb. 2012 Production"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="A20">
		<pin no="1">
			<line id="18" color="Y">
				<connector type="w2w" code="IH1" sex="male">
					<pin no="1"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="w2w" code="IH1" sex="female">
		<pin no="1">
			<line id="19" color="Y-R">
				<connector type="conn" code="A19">
					<pin no="4"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="A20">
		<pin no="2">
			<line id="20" color="Y-B">
				<connector type="w2w" code="IH1" sex="male">
					<pin no="2"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="w2w" code="IH1" sex="female">
		<pin no="2">
			<line id="21" color="Y-G">
				<connector type="conn" code="A19">
					<pin no="3"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="A19">
		<pin no="27">
			<line id="22" color="BR-W">
				<connector type="w2w" code="II1" sex="male">
					<pin no="2"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="w2w" code="II1" sex="female">
		<pin no="2">
			<line id="23" color="BR-W">
				<connector type="conn" code="A6" subcode="A">
					<pin no="1" spec="Before Feb. 2012 Production"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="w2w" code="II1" sex="female">
		<pin no="2">
			<line id="23" color="BR-W">
				<connector type="conn" code="A33" subcode="B">
					<pin no="1" spec="From Feb. 2012 Production"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="A19">
		<pin no="29">
			<line id="24" color="B-W">
				<connector type="w2w" code="II1" sex="male">
					<pin no="1"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="w2w" code="II1" sex="female">
		<pin no="1">
			<line id="25" color="B-W">
				<connector type="conn" code="A6" subcode="A">
					<pin no="2" spec="Before Feb. 2012 Production"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="w2w" code="II1" sex="female">
		<pin no="1">
			<line id="25" color="B-W">
				<connector type="conn" code="A33" subcode="B">
					<pin no="2" spec="From Feb. 2012 Production"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="gp" code="IG">
		<pin>
			<line id="26" color="W-B">
				<connector type="jbc" code="2D">
					<pin no="18"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="jbc" code="2B">
		<pin no="1">
			<line id="27" color="W-B">
				<connector type="conn" code="A19">
					<pin no="25"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="A39">
		<pin no="1">
			<line id="28" color="Y" spec="From Mar. 2013 Production">
				<connector type="conn" code="F18">
					<pin no="2"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="A39">
		<pin no="2">
			<line id="29" color="Y-B" spec="From Mar. 2013 Production">
				<connector type="conn" code="F18">
					<pin no="1"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="gp" code="IH">
		<pin>
			<line id="30" color="W-B">
				<connector type="jbc" code="2D">
					<pin no="9"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="jbc" code="2B">
		<pin no="2">
			<line id="31" color="W-B">
				<connector type="conn" code="A19">
					<pin no="26"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="E10" subcode="B">
		<pin no="32">
			<line id="32" color="B">
				<connector type="w2w" code="IF1" sex="male">
					<pin no="2"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="w2w" code="IF1" sex="female">
		<pin no="2">
			<line id="33" color="B">
				<connector type="conn" code="A19">
					<pin no="22"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="A40">
		<pin no="5">
			<line id="34" color="Y" spec="From Mar. 2013 Production">
				<connector type="conn" code="F17">
					<pin no="2"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="A40">
		<pin no="4">
			<line id="35" color="Y-B" spec="From Mar. 2013 Production">
				<connector type="conn" code="F17">
					<pin no="1"/>
				</connector>
			</line>
		</pin>
	</connector>
</connectionList>

=== lequockhanh19521680/KhangSave/innova 2015/rm21q3ev/ewd/contents/system/connect/PW.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE connectionList SYSTEM "../../../dtd/connect.dtd">
<connectionList pubno="EM21Q2EV">
	<connector type="rb" code="3">
		<pin>
			<line id="1" color="L">
				<connector type="conn" code="J21" subcode="A">
					<pin no="1"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="J33">
		<pin no="1">
			<line id="2" color="W-B">
				<connector type="w2w" code="IC1" sex="male">
					<pin no="4"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="w2w" code="IC1" sex="female">
		<pin no="4">
			<line id="3" color="W-B">
				<connector type="conn" code="P5">
					<pin no="3"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="J18" subcode="A">
		<pin no="1">
			<line id="4" color="L">
				<connector type="conn" code="J22" subcode="B">
					<pin no="5"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="J21" subcode="A">
		<pin no="2">
			<line id="5" color="L">
				<connector type="conn" code="J31" subcode="A">
					<pin no="1"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="J32" subcode="B">
		<pin no="6">
			<line id="6" color="L">
				<connector type="conn" code="P10">
					<pin no="3"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="J19" subcode="B">
		<pin no="6">
			<line id="7" color="L">
				<connector type="conn" code="P5">
					<pin no="6"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="J18" subcode="A">
		<pin no="2">
			<line id="8" color="L">
				<connector type="w2w" code="BB1" sex="male">
					<pin no="8"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="J31" subcode="A">
		<pin no="2">
			<line id="9" color="L">
				<connector type="w2w" code="BC1" sex="male">
					<pin no="8"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="P6">
		<pin no="2">
			<line id="10" color="R">
				<connector type="conn" code="P5">
					<pin no="4"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="P6">
		<pin no="1">
			<line id="11" color="L-R">
				<connector type="conn" code="P5">
					<pin no="9"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="P7">
		<pin no="2">
			<line id="12" color="R">
				<connector type="conn" code="P10">
					<pin no="2"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="P10">
		<pin no="1">
			<line id="13" color="R-L">
				<connector type="w2w" code="IL1" sex="female">
					<pin no="3"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="w2w" code="IL1" sex="male">
		<pin no="3">
			<line id="14" color="R-L">
				<connector type="w2w" code="IC1" sex="male">
					<pin no="10"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="w2w" code="IC1" sex="female">
		<pin no="10">
			<line id="15" color="R-L">
				<connector type="conn" code="P5">
					<pin no="18"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="P10">
		<pin no="4">
			<line id="16" color="G-W">
				<connector type="w2w" code="IL1" sex="female">
					<pin no="4"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="w2w" code="IL1" sex="male">
		<pin no="4">
			<line id="17" color="G-W">
				<connector type="w2w" code="IC1" sex="male">
					<pin no="3"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="w2w" code="IC1" sex="female">
		<pin no="3">
			<line id="18" color="G-W">
				<connector type="conn" code="P5">
					<pin no="15"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="P7">
		<pin no="1">
			<line id="19" color="L-R">
				<connector type="conn" code="P10">
					<pin no="5"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="w2w" code="BB1" sex="female">
		<pin no="8">
			<line id="20" color="L">
				<connector type="conn" code="P11">
					<pin no="3"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="P8">
		<pin no="2">
			<line id="21" color="R">
				<connector type="conn" code="P11">
					<pin no="2"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="P11">
		<pin no="1">
			<line id="22" color="R-B">
				<connector type="w2w" code="BB1" sex="female">
					<pin no="6"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="w2w" code="BB1" sex="male">
		<pin no="6">
			<line id="23" color="R-Y">
				<connector type="w2w" code="IC1" sex="male">
					<pin no="2"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="w2w" code="IC1" sex="female">
		<pin no="2">
			<line id="24" color="R-Y">
				<connector type="conn" code="P5">
					<pin no="12"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="P11">
		<pin no="4">
			<line id="25" color="G-B">
				<connector type="w2w" code="BB1" sex="female">
					<pin no="7"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="w2w" code="BB1" sex="male">
		<pin no="7">
			<line id="26" color="G-Y">
				<connector type="w2w" code="IC1" sex="male">
					<pin no="1"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="w2w" code="IC1" sex="female">
		<pin no="1">
			<line id="27" color="G-Y">
				<connector type="conn" code="P5">
					<pin no="13"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="P8">
		<pin no="1">
			<line id="28" color="L-R">
				<connector type="conn" code="P11">
					<pin no="5"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="w2w" code="BC1" sex="female">
		<pin no="8">
			<line id="29" color="L">
				<connector type="conn" code="P12">
					<pin no="3"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="P9">
		<pin no="2">
			<line id="30" color="R">
				<connector type="conn" code="P12">
					<pin no="2"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="P12">
		<pin no="1">
			<line id="31" color="R-B">
				<connector type="w2w" code="BC1" sex="female">
					<pin no="6"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="w2w" code="BC1" sex="male">
		<pin no="6">
			<line id="32" color="R-B">
				<connector type="w2w" code="IC1" sex="male">
					<pin no="6"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="w2w" code="IC1" sex="female">
		<pin no="6">
			<line id="33" color="R-B">
				<connector type="conn" code="P5">
					<pin no="10"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="P12">
		<pin no="4">
			<line id="34" color="G-B">
				<connector type="w2w" code="BC1" sex="female">
					<pin no="7"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="w2w" code="BC1" sex="male">
		<pin no="7">
			<line id="35" color="G-B">
				<connector type="w2w" code="IC1" sex="male">
					<pin no="5"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="w2w" code="IC1" sex="female">
		<pin no="5">
			<line id="36" color="G-B">
				<connector type="conn" code="P5">
					<pin no="16"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="P9">
		<pin no="1">
			<line id="37" color="L-R">
				<connector type="conn" code="P12">
					<pin no="5"/>
				</connector>
			</line>
		</pin>
	</connector>
</connectionList>

=== lequockhanh19521680/KhangSave/innova 2015/rm21q3ev/ewd/contents/system/connect/AC-REA.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE connectionList SYSTEM "../../../dtd/connect.dtd">
<connectionList pubno="EM21Q2EV">
	<connector type="conn" code="R8">
		<pin no="5">
			<line id="1" color="L-B">
				<connector type="conn" code="B12">
					<pin no="4"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="R8">
		<pin no="3">
			<line id="2" color="R-L">
				<connector type="conn" code="J21" subcode="A">
					<pin no="8"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="J21" subcode="A">
		<pin no="7">
			<line id="3" color="R-L">
				<connector type="jbc" code="2K">
					<pin no="8"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="R8">
		<pin no="2">
			<line id="4" color="L">
				<connector type="conn" code="B10">
					<pin no="2"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="R8">
		<pin no="1">
			<line id="5" color="R">
				<connector type="w2w" code="IJ1" sex="male">
					<pin no="2" spec="Before Sep. 2009 Production"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="R8">
		<pin no="1">
			<line id="5" color="R">
				<connector type="w2w" code="IJ3" sex="male">
					<pin no="2" spec="From Sep. 2009 Production until Sep. 2010 Production"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="R8">
		<pin no="1">
			<line id="5" color="R">
				<connector type="w2w" code="IJ5" sex="male">
					<pin no="2" spec="From Sep. 2010 Production until Feb. 2012 Production"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="R8">
		<pin no="1">
			<line id="5" color="R">
				<connector type="w2w" code="IJ6" sex="male">
					<pin no="10" spec="From Feb. 2012 Production"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="R8">
		<pin no="4">
			<line id="6" color="W-B">
				<connector type="conn" code="J33">
					<pin no="6"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="sp" code="1249">
		<pin>
			<line id="7" color="R-B">
				<connector type="conn" code="B12">
					<pin no="1"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="sp" code="1249">
		<pin>
			<line id="8" color="R-B">
				<connector type="conn" code="B10">
					<pin no="1"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="sp" code="1249">
		<pin>
			<line id="9" color="R-B">
				<connector type="conn" code="B11">
					<pin no="1"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="w2w" code="IJ1" sex="female">
		<pin no="2" spec="Before Sep. 2009 Production">
			<line id="10" color="R">
				<connector type="jbc" code="1B">
					<pin no="2" spec="From Sep. 2008 Production"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="w2w" code="IJ1" sex="female">
		<pin no="2" spec="Before Sep. 2009 Production">
			<line id="10" color="R">
				<connector type="jbc" code="1D">
					<pin no="1" spec="Before Sep. 2008 Production"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="w2w" code="IJ3" sex="female">
		<pin no="2" spec="From Sep. 2009 Production until Sep. 2010 Production">
			<line id="10" color="R">
				<connector type="jbc" code="1B">
					<pin no="2" spec="From Sep. 2008 Production"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="w2w" code="IJ3" sex="female">
		<pin no="2" spec="From Sep. 2009 Production until Sep. 2010 Production">
			<line id="10" color="R">
				<connector type="jbc" code="1D">
					<pin no="1" spec="Before Sep. 2008 Production"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="w2w" code="IJ5" sex="female">
		<pin no="2" spec="From Sep. 2010 Production until Feb. 2012 Production">
			<line id="10" color="R">
				<connector type="jbc" code="1B">
					<pin no="2" spec="From Sep. 2008 Production"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="w2w" code="IJ5" sex="female">
		<pin no="2" spec="From Sep. 2010 Production until Feb. 2012 Production">
			<line id="10" color="R">
				<connector type="jbc" code="1D">
					<pin no="1" spec="Before Sep. 2008 Production"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="w2w" code="IJ6" sex="female">
		<pin no="10" spec="From Feb. 2012 Production">
			<line id="10" color="R">
				<connector type="jbc" code="1B">
					<pin no="2" spec="From Sep. 2008 Production"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="w2w" code="IJ6" sex="female">
		<pin no="10" spec="From Feb. 2012 Production">
			<line id="10" color="R">
				<connector type="jbc" code="1D">
					<pin no="1" spec="Before Sep. 2008 Production"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="B12">
		<pin no="2">
			<line id="11" color="Y-R">
				<connector type="conn" code="B11">
					<pin no="3"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="B12">
		<pin no="3">
			<line id="12" color="V">
				<connector type="conn" code="B11">
					<pin no="2"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="J33">
		<pin no="4">
			<line id="13" color="W-B" spec="Before Sep. 2008 Production">
				<connector type="conn" code="B12">
					<pin no="5"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="B12">
		<pin no="5">
			<line id="14" color="W-B" spec="From Sep. 2008 Production">
				<connector type="conn" code="J33">
					<pin no="10"/>
				</connector>
			</line>
		</pin>
	</connector>
	<connector type="conn" code="B11">
		<pin no="4">
			<line id="15" color="W-B">
				<connector type="conn" code="J33">
					<pin no="7"/>
				</connector>
			</line>
		</pin>
	</connector>
</connectionList>
