=== lequockhanh19521680/KhangSave/innova 2015/rm21q3ev/ewd/dtd/ewdpub.dtd
<!--
   EWD DTD

   Copyright (c) 2000-2003 SHINTEC HOZUMI Co.,LTD.
   All Rights Reserved. 


  for EWD Service Category Type
-->
<!-- <?xml version="1.0" encoding="UTF-8"?> -->
<!-- XML DTD for TOYOTA EWD -->
<!ENTITY % CountryCode
	"(en | fr | de | es | pt | it | sv | da | fi | no | nl | el | cs | hu | pl | ja)"
>

<!ELEMENT	pub (files)+>
<!ATTLIST	pub
	ver	CDATA	"1.0"
	no	CDATA	#REQUIRED
	xml:lang %CountryCode; #REQUIRED
	modelname CDATA #REQUIRED
	modelyear CDATA #REQUIRED
	distributor CDATA #REQUIRED
	marketingdivision (toyota|lexus|scion) "toyota"
>

<!ELEMENT files (file)+>
<!ELEMENT file EMPTY>
<!ATTLIST	file
	path	CDATA	#REQUIRED
>

=== lequockhanh19521680/KhangSave/innova 2015/rm21q3ev/ewd/contents/ewdpub.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pub SYSTEM "../dtd/ewdpub.dtd">
<pub ver="1.0" xml:lang="en" no="EM21Q2EV" modelname="TOYOTA INNOVA" modelyear="2014" distributor="E" marketingdivision="toyota">
	<files>
		<file path="ewdpub.xml"/>
		<file path="ewd_main.html"/>
		<file path="index.html"/>
		<file path="navi_bar.html"/>
		<file path="popup.html"/>
		<file path="select.html"/>
		<file path="common\dialog.html"/>
		<file path="common\dialog_header.html"/>
		<file path="common\figctrl.html"/>
		<file path="common\figmap.html"/>
		<file path="common\figtitle.html"/>
		<file path="common\fig_frame.html"/>
		<file path="common\fig_subframe.html"/>
		<file path="common\print.html"/>
		<file path="common\print_header.html"/>
		<file path="connector\connect.html"/>
		<file path="connector\parts.html"/>
		<file path="connector\parts.xml"/>
		<file path="connector\partscode.xml"/>
		<file path="connector\partslist.html"/>
		<file path="connector\partslist_code.html"/>
		<file path="connector\partslist_name.html"/>
		<file path="connector\partslist_no.html"/>
		<file path="connector\partsref.html"/>
		<file path="connector\partsref_print.html"/>
		<file path="connector\pinfo.html"/>
		<file path="connector\plist.html"/>
		<file path="connector\psearch.html"/>
		<file path="connector\repair.html"/>
		<file path="connector\sysrefs.xml"/>
		<file path="connector\terminfo.html"/>
		<file path="connector\fig\6098-4462.svgz"/>
		<file path="connector\fig\6098-4463.svgz"/>
		<file path="connector\fig\82660-20340.svgz"/>
		<file path="connector\fig\82675-34020.svgz"/>
		<file path="connector\fig\82824-0K010.svgz"/>
		<file path="connector\fig\82824-0K020.svgz"/>
		<file path="connector\fig\82824-0K030.svgz"/>
		<file path="connector\fig\82824-0K040.svgz"/>
		<file path="connector\fig\82824-0K050.svgz"/>
		<file path="connector\fig\82824-52130.svgz"/>
		<file path="connector\fig\82824-60460.svgz"/>
		<file path="connector\fig\90080-98298.svgz"/>
		<file path="connector\fig\90980-09212.svgz"/>
		<file path="connector\fig\90980-09506.svgz"/>
		<file path="connector\fig\90980-09567.svgz"/>
		<file path="connector\fig\90980-09582.svgz"/>
		<file path="connector\fig\90980-10619.svgz"/>
		<file path="connector\fig\90980-10713.svgz"/>
		<file path="connector\fig\90980-10735.svgz"/>
		<file path="connector\fig\90980-10760.svgz"/>
		<file path="connector\fig\90980-10789.svgz"/>
		<file path="connector\fig\90980-10794.svgz"/>
		<file path="connector\fig\90980-10795.svgz"/>
		<file path="connector\fig\90980-10796.svgz"/>
		<file path="connector\fig\90980-10797.svgz"/>
		<file path="connector\fig\90980-10798.svgz"/>
		<file path="connector\fig\90980-10799.svgz"/>
		<file path="connector\fig\90980-10800.svgz"/>
		<file path="connector\fig\90980-10801.svgz"/>
		<file path="connector\fig\90980-10803.svgz"/>
		<file path="connector\fig\90980-10806.svgz"/>
		<file path="connector\fig\90980-10807.svgz"/>
		<file path="connector\fig\90980-10825.svgz"/>
		<file path="connector\fig\90980-10830.svgz"/>
		<file path="connector\fig\90980-10843.svgz"/>
		<file path="connector\fig\90980-10860.svgz"/>
		<file path="connector\fig\90980-10871.svgz"/>
		<file path="connector\fig\90980-10877.svgz"/>
		<file path="connector\fig\90980-10878.svgz"/>
		<file path="connector\fig\90980-10879.svgz"/>
		<file path="connector\fig\90980-10891.svgz"/>
		<file path="connector\fig\90980-10896.svgz"/>
		<file path="connector\fig\90980-10897.svgz"/>
		<file path="connector\fig\90980-10906.svgz"/>
		<file path="connector\fig\90980-10908.svgz"/>
		<file path="connector\fig\90980-10916.svgz"/>
		<file path="connector\fig\90980-10927.svgz"/>
		<file path="connector\fig\90980-10928.svgz"/>
		<file path="connector\fig\90980-10935.svgz"/>
		<file path="connector\fig\90980-10947.svgz"/>
		<file path="connector\fig\90980-10962.svgz"/>
		<file path="connector\fig\90980-10964.svgz"/>
		<file path="connector\fig\90980-10976.svgz"/>
		<file path="connector\fig\90980-10979.svgz"/>
		<file path="connector\fig\90980-10980.svgz"/>
		<file path="connector\fig\90980-10987.svgz"/>
		<file path="connector\fig\90980-10988.svgz"/>
		<file path="connector\fig\90980-10995.svgz"/>
		<file path="connector\fig\90980-10996.svgz"/>
		<file path="connector\fig\90980-10997.svgz"/>
		<file path="connector\fig\90980-10998.svgz"/>
		<file path="connector\fig\90980-11001.svgz"/>
		<file path="connector\fig\90980-11003.svgz"/>
		<file path="connector\fig\90980-11011.svgz"/>
		<file path="connector\fig\90980-11012.svgz"/>
		<file path="connector\fig\90980-11013.svgz"/>
		<file path="connector\fig\90980-11016.svgz"/>
		<file path="connector\fig\90980-11019.svgz"/>
		<file path="connector\fig\90980-11025.svgz"/>
		<file path="connector\fig\90980-11028.svgz"/>
		<file path="connector\fig\90980-11051.svgz"/>
		<file path="connector\fig\90980-11060.svgz"/>
		<file path="connector\fig\90980-11070.svgz"/>
		<file path="connector\fig\90980-11075.svgz"/>
		<file path="connector\fig\90980-11077.svgz"/>
		<file path="connector\fig\90980-11093.svgz"/>
		<file path="connector\fig\90980-11094.svgz"/>
		<file path="connector\fig\90980-11101.svgz"/>
		<file path="connector\fig\90980-11118.svgz"/>
		<file path="connector\fig\90980-11136.svgz"/>
		<file path="connector\fig\90980-11143.svgz"/>
		<file path="connector\fig\90980-11148.svgz"/>
		<file path="connector\fig\90980-11149.svgz"/>
		<file path="connector\fig\90980-11155.svgz"/>
		<file path="connector\fig\90980-11156.svgz"/>
		<file path="connector\fig\90980-11162.svgz"/>
		<file path="connector\fig\90980-11207.svgz"/>
		<file path="connector\fig\90980-11212.svgz"/>
		<file path="connector\fig\90980-11246.svgz"/>
		<file path="connector\fig\90980-11250.svgz"/>
		<file path="connector\fig\90980-11271.svgz"/>
		<file path="connector\fig\90980-11314.svgz"/>
		<file path="connector\fig\90980-11317.svgz"/>
		<file path="connector\fig\90980-11363.svgz"/>
		<file path="connector\fig\90980-11398.svgz"/>
		<file path="connector\fig\90980-11400.svgz"/>
		<file path="connector\fig\90980-11428.svgz"/>
		<file path="connector\fig\90980-11452.svgz"/>
		<file path="connector\fig\90980-11528.svgz"/>
		<file path="connector\fig\90980-11529.svgz"/>
		<file path="connector\fig\90980-11530.svgz"/>
		<file path="connector\fig\90980-11531.svgz"/>
		<file path="connector\fig\90980-11536.svgz"/>
		<file path="connector\fig\90980-11537.svgz"/>
		<file path="connector\fig\90980-11539.svgz"/>
		<file path="connector\fig\90980-11541.svgz"/>
		<file path="connector\fig\90980-11542.svgz"/>
		<file path="connector\fig\90980-11579.svgz"/>
		<file path="connector\fig\90980-11583.svgz"/>
		<file path="connector\fig\90980-11599.svgz"/>
		<file path="connector\fig\90980-11608.svgz"/>
		<file path="connector\fig\90980-11615.svgz"/>
		<file path="connector\fig\90980-11655.svgz"/>
		<file path="connector\fig\90980-11657.svgz"/>
		<file path="connector\fig\90980-11660.svgz"/>
		<file path="connector\fig\90980-11661.svgz"/>
		<file path="connector\fig\90980-11676.svgz"/>
		<file path="connector\fig\90980-11742.svgz"/>
		<file path="connector\fig\90980-11772.svgz"/>
		<file path="connector\fig\90980-11775.svgz"/>
		<file path="connector\fig\90980-11856.svgz"/>
		<file path="connector\fig\90980-11858.svgz"/>
		<file path="connector\fig\90980-11875.svgz"/>
		<file path="connector\fig\90980-11883.svgz"/>
		<file path="connector\fig\90980-11884.svgz"/>
		<file path="connector\fig\90980-11885.svgz"/>
		<file path="connector\fig\90980-11891.svgz"/>
		<file path="connector\fig\90980-11892.svgz"/>
		<file path="connector\fig\90980-11900.svgz"/>
		<file path="connector\fig\90980-11909.svgz"/>
		<file path="connector\fig\90980-11911.svgz"/>
		<file path="connector\fig\90980-11912.svgz"/>
		<file path="connector\fig\90980-11913.svgz"/>
		<file path="connector\fig\90980-11915.svgz"/>
		<file path="connector\fig\90980-11917.svgz"/>
		<file path="connector\fig\90980-11918.svgz"/>
		<file path="connector\fig\90980-11964.svgz"/>
		<file path="connector\fig\90980-11971.svgz"/>
		<file path="connector\fig\90980-11973.svgz"/>
		<file path="connector\fig\90980-11978.svgz"/>
		<file path="connector\fig\90980-12007.svgz"/>
		<file path="connector\fig\90980-12012.svgz"/>
		<file path="connector\fig\90980-12020.svgz"/>
		<file path="connector\fig\90980-12025.svgz"/>
		<file path="connector\fig\90980-12063.svgz"/>
		<file path="connector\fig\90980-12092.svgz"/>
		<file path="connector\fig\90980-12111.svgz"/>
		<file path="connector\fig\90980-12122.svgz"/>
		<file path="connector\fig\90980-12155.svgz"/>
		<file path="connector\fig\90980-12160.svgz"/>
		<file path="connector\fig\90980-12169.svgz"/>
		<file path="connector\fig\90980-12183.svgz"/>
		<file path="connector\fig\90980-12204.svgz"/>
		<file path="connector\fig\90980-12221.svgz"/>
		<file path="connector\fig\90980-12224.svgz"/>
		<file path="connector\fig\90980-12226.svgz"/>
		<file path="connector\fig\90980-12253.svgz"/>
		<file path="connector\fig\90980-12259.svgz"/>
		<file path="connector\fig\90980-12272.svgz"/>
		<file path="connector\fig\90980-12273.svgz"/>
		<file path="connector\fig\90980-12303.svgz"/>
		<file path="connector\fig\90980-12304.svgz"/>
		<file path="connector\fig\90980-12331.svgz"/>
		<file path="connector\fig\90980-12332.svgz"/>
		<file path="connector\fig\90980-12358.svgz"/>
		<file path="connector\fig\90980-12359.svgz"/>
		<file path="connector\fig\90980-12362.svgz"/>
		<file path="connector\fig\90980-12365.svgz"/>
		<file path="connector\fig\90980-12366.svgz"/>
		<file path="connector\fig\90980-12391.svgz"/>
		<file path="connector\fig\90980-12404.svgz"/>
		<file path="connector\fig\90980-12409.svgz"/>
		<file path="connector\fig\90980-12410.svgz"/>
		<file path="connector\fig\90980-12449.svgz"/>
		<file path="connector\fig\90980-12450.svgz"/>
		<file path="connector\fig\90980-12485.svgz"/>
		<file path="connector\fig\90980-12486.svgz"/>
		<file path="connector\fig\90980-12490.svgz"/>
		<file path="connector\fig\90980-12498.svgz"/>
